version: '3.8'

services:
  graphdb:
    container_name: graphdb
    image: falkordb/falkordb:edge
    ports:
      - "6379:6379"
      - "3000:3000"
    volumes:
      - falkordb-data:/data
    environment:
      - REDIS_ARGS=--requirepass falkordb

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - graphdb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  falkordb-data:
    driver: local
