### Variables setup
@host = http://localhost:8000

### Redirect to Docs
GET {{host}}/
Accept: application/json

### Create New Case
POST {{host}}/api/v1/cases/create_new_case
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="case_name"

Mor123

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="Deposition of Emergency Room Nurse in Medical Malpractice Lawsuit.txt"
Content-Type: text/plain

< /Users/mordvash/mor/HIT/legal_assistant/backend/src/dev_env/Deposition of Emergency Room Nurse in Medical Malpractice Lawsuit.txt
--WebAppBoundary

### List all cases
GET {{host}}/api/v1/cases/list_cases
Accept: application/json

### serach case
POST {{host}}/api/v1/cases/Mor123/search
Content-Type: application/json

{
    "question": "who is Tolson?",
    "response_mod": "tree_summarize"
}

### Get case(Graph)
GET {{host}}/api/v1/cases/Mor
Accept: application/json

### Delete file
DELETE {{host}}/api/v1/cases/Mor123
Accept: application/json