version: '3.8'

services:
  graphdb:
    container_name: graphdb
    image: falkordb/falkordb:edge
    ports:
      - "6379:6379"
      - "3000:3000"
    volumes:
      - falkordb-data:/data
    environment:
      - REDIS_ARGS=--requirepass falkordb

  backend:
    build:
      context: ../../.
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    depends_on:
      - graphdb

volumes:
  falkordb-data:
    driver: local
