name: pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install --upgrade pip
          pip install poetry==1.7.0
          poetry config virtualenvs.create false
          poetry install --no-interaction

      - name: Run pytest
        working-directory: backend
        env:
          OPENAI_API_KEY: "test_openai_key"
          GEMINI_KEY: "test_gemini_key"
          FALKORDB_PASSWORD: "test_password"
          FALKORDB_RAG_URI: "test_uri"
        run: |
            # List the contents to verify the structure
            echo "Contents of unit_tests directory:"
            ls -la tests/unit_tests/
            
            # Run pytest with the correct path
            python -m pytest tests/unit_tests