name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-3.12

      - name: Install tox & poetry
        working-directory: backend
        run: |
          pip install --upgrade pip
          pip install poetry==1.7.0
          pip install tox
      - name: run tests
        run: tox
